<?php
function greeting_menu() {
  $items = array();
  $items['hello_friend'] = array(
    'title' => 'hello friend!',
    'page callback' => 'say_hello',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['farewell'] = array(
    'title' => 'farewell friend',
    'page callback' => 'say_farewell',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['specials'] = array(
    'title' => 'Services Menu',
    'page callback' => 'menu_display',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['api'] = array(
    'title' => 'companies',
    'page callback' => 'api',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function say_hello() {
  $name = "Sarah";
  return '<p> Hello my friend' . $name  . '</p>';
}

function say_farewell() {
  return '<p>So long, farewell</p>';
}

function menu_display() {
  return '
  <ul>
    <li>View company profiles</li>
    <li>Add company profiles</li>
    <li>edit company profiles</li>
    <li>Rate companies</li>
    </ul>
    ';
}

function api() {
$glassdoor = 'http://api.glassdoor.com/api/api.htm?v=1&format=json&t.p=142977&t.k=cEGqsXg9JMY&action=employers&q=tech&userip=192.168.43.42&useragent=Mozilla/%2F4.0&action=employers';
$result = file_get_contents($glassdoor);
$jobs_array = json_decode($result, true);
$companies = $jobs_array['response']["employers"];
$company_names = '<ul>';
for($i = 0; $i<count($companies); $i++) {
    $company_name = $companies[$i]['name'];
    $company_names = $company_names . '<li>' . $company_name . '</li>';
}
$company_names = $company_names . '</ul>';
return $company_names;
}
